### ISSUE TITLE
Implement parser for EXPRESS syntax

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#1]
1. Modify the IFC “[Express.g4](https://github.com/hypar-io/IFC-gen/blob/IFC4/grammar/Express.g4)” grammar to parse proper EXPRESS (ISO 10303-11) syntax. The EXPRESS language reference will be provided. 

2. Test the generated Ruby parser code to ensure all existing EXPRESS files (.exp files) can be parsed properly.

3. Link the EXPRESS parser parse tree to their representations in EXPRESS (located in https://github.com/lutaml/expressr/tree/master/lib/expressr/express)

**Comment by ronaldtse** [comment]
Ping @abunashir do you have time for this? Thanks!

**Comment by abunashir** [comment]
Yap, I will add it to my list.

**Comment by ronaldtse** [comment]
@zakjan is going to handle this, thanks!

**Comment by ronaldtse** [comment]
@abunashir @zakjan this repo has been renamed to Expressir, just FYI.
