### ISSUE TITLE
Build arm64-linux version for arm64

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#104]
Similar to https://github.com/metanorma/emf2svg-ruby/pull/16

**Comment by ronaldtse** [comment]
FYI @maxirmx when you have time. expressir also needs a platform gem for Windows and arm/Apple M1. Thanks!

**Comment by maxirmx** [comment]
@ronaldtse 
It looks like this gem is all set
![image](https://user-images.githubusercontent.com/2081498/159969244-db16a139-8567-46cf-aa73-7b19847e009b.png)

**Comment by ronaldtse** [comment]
Nearly!

I see these two files doing the work:
- https://github.com/lutaml/expressir/blob/862815313231c15ffc05d98c4b49dc80f85ad464/.cross_rubies
- https://github.com/lutaml/expressir/blob/5a7d9615cf187d04549ef4bb4c6152f76b48235b/rakelib/cross-ruby.rake

 We need arm64-linux but it is not in the list yet.

**Comment by ronaldtse** [comment]
Maybe we just need to change those two files and we can add all the necessary platforms?

**Comment by maxirmx** [comment]
I see, thank you
