### ISSUE TITLE
Upgrade antlr generator to 4.10

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#114]
Antlr project already fixed this issue.  I updated the version we use from 4.8 to 4.9
Note: Could not upgrade to the latest antlr 4.10 since it is major update with API change

_Originally posted by @maxirmx in https://github.com/lutaml/expressir/pull/112#discussion_r864683300_

**Comment by maxirmx** [comment]
https://github.com/camertron/antlr4-native-rb/issues/12

**Comment by maxirmx** [comment]
Expressir built with  antlr 4.10.1 / antlr4-native-rb 2.1.0   is unstable
This update has been removed from https://github.com/lutaml/expressir/pull/116
