### ISSUE TITLE
Add Ruby 3.2 support

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#134]
Add Ruby 3.2 to build matrix

**Comment by ronaldtse** [comment]
Expressir core dumps on Ruby 3.2 when encountering a schema it can't parse properly. This is shown in the stepmod-utils tests:

- https://github.com/metanorma/stepmod-utils/actions/runs/7138119001/job/19439213168

**Comment by maxirmx** [comment]
I think we need to update rake-compiler-dock in order to build 3.2 version correctly
Let me check
