### ISSUE TITLE
Parsing speed mitigation: model cache

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#14]
Even with #13 implemented, I believe we probably need a model cache to store the parsed parse tree for quick lookup.

This task is to implement a model cache (e.g. serialized form of the parsed parse tree) in a single file. The easiest way is to store the Ruby parse tree via model serialization, but an interpretable text-format cache e.g. in YAML would be much preferable. (perhaps each model `.rb` class will have a `to_yaml` method)

Save:
```ruby
repo = Expressir::ExpressExp::Parser.from_exp(file)
repo.save('my-model-cache.yaml')
```

Load:
```ruby
repo = Expressir::ExpressExp::Parser.load('my-model-cache.yaml')
schema = repo.schemas.find{|schema| schema.id == "action_schema"}
...
```

**Comment by zakjan** [comment]
Replaced by #33
