### ISSUE TITLE
Expressir 1.3.0 installation issue

### ISSUE THREAD

**Issue by Intelligent2013** [lutaml/expressir#143]
The issue occurs in the installation of `expressir-1.3.0`.

This issue blocks the task https://github.com/metanorma/metanorma-standoc/issues/844.

From https://github.com/metanorma/mn-native-pdf/actions/runs/7340488721/job/19986570979:
```
...
Fetching expressir 1.3.0 (x86_64-linux)

Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/expressir-1.3.0-x86_64-linux.gem)
Installing nokogiri 1.15.5 (x86_64-linux)

Retrying download gem from https://rubygems.org/ due to error (3/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/expressir-1.3.0-x86_64-linux.gem)

Retrying download gem from https://rubygems.org/ due to error (4/4): Gem::RemoteFetcher::FetchError bad response Forbidden 403 (https://rubygems.org/gems/expressir-1.3.0-x86_64-linux.gem)
...
```

I.e. ruby tries to install the gem `https://rubygems.org/gems/expressir-1.3.0-x86_64-linux.gem`, but the real URL is 
`https://rubygems.org/gems/expressir-1.3.0-x86_64-linux-gnu.gem` (with `-gnu` suffix).
The previous version `1.2.11`  doesn't have the suffix `-gnu` https://rubygems.org/downloads/expressir-1.2.11-x86_64-linux.gem

The suffix `-gnu` was added in:
https://github.com/lutaml/expressir/blob/33b6a7e7c853d088356acc3c7085a6a9d54aea3f/.github/workflows/rake.yml#L128

How to update https://github.com/metanorma/mn-native-pdf/blob/master/.github/workflows/ubuntu.yml? Or is there the issue in expressir?

**Comment by ronaldtse** [comment]
This is a bug in rubygems that it cannot handle the platform code. The solution is to upgrade rubygems, can you check Metanorma/ci repo for the latest changes?

**Comment by maxirmx** [comment]
@Intelligent2013 for Ruby 2.7.8
rubygems 3.4.22 is required
2.7 is not supported (by bundler/rubygems team)  though it is possible to make it work

If you expreience is locally I would strongly recommend to use Ruby 3.1    
As for ci scripts I believe @CAMOBAP has updated them

**Comment by maxirmx** [comment]
UPD 
Workflows like [mn-native-pdf](https://github.com/metanorma/mn-native-pdf/tree/master) that do not use metanorma test matrix need to be updated to 3.1 as well

**Comment by CAMOBAP** [comment]
> As for ci scripts I believe @CAMOBAP has updated them

I hope so
But in case if you observed the issue on some other repos don't hesitate to ping me

**Comment by Intelligent2013** [comment]
I've updated ruby 2.7 to 3.1 in mn-native-pdf. It solved the issue.
Thank you @maxirmx !
