### ISSUE TITLE
Migrate Expressir::Express classes to use Expressir::Model classes

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#15]
The older set of EXPRESS classes are under the namespace of `Expressir::Express`, such as: `Expressir::Express::AggregateDimension`.

The new set of EXPRESS classes are under `Expressir::Model`, e.g. `Expressir::Model::Statements`.

This task is to replace the older set with the new classes.

**Comment by zakjan** [comment]
This is going to enable import/export from/to any format.
