### ISSUE TITLE
401 Unauthorized Access Denied. Please sign up for an account at https://rubygems.org

### ISSUE THREAD

**Issue by CAMOBAP** [lutaml/expressir#36]
https://github.com/lutaml/expressir/runs/1617122636?check_suite_focus=true

@ronaldtse could you please double-check that LUTAML_CI_RUBYGEMS_API_KEY contains valid API_KEY

**Comment by ronaldtse** [comment]
Good find -- yes it's now fixed. Thanks!

**Comment by ronaldtse** [comment]
It didn't work because the `~/.gem/credentials` file did not contain the interpolated API key but the actual string. Trying again now.

**Comment by CAMOBAP** [comment]
@ronaldtse unfortunatelly it still doesn't work ( 

May I ask you to double-check `LUTAML_CI_RUBYGEMS_API_KEY ` value in with `curl -u metanorma https://rubygems.org/api/v1/api_key.yaml` output?

**Comment by CAMOBAP** [comment]
@ronaldtse this till a problem for us, we need to make sure that `LUTAML_CI_RUBYGEMS_API_KEY` is correct one

**Comment by ronaldtse** [comment]
@CAMOBAP as mentioned, the API key is 100% correct...

**Comment by CAMOBAP** [comment]
@ronaldtse you are right, there was a strange issue with the key, I still don't know why but without passing a key it just works
