### ISSUE TITLE
Source gem installation error

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#37]
It seems that some paths need to be fixed in the compilation process? Ahh this file is only available via submodule. It must be included in the gem itself during build. We need to update the gemspec to include these files.

The `antlr4-runtime.h` file is available here:
<img width="356" alt="Screen Shot 2020-12-29 at 11 30 12 AM" src="https://user-images.githubusercontent.com/11865/103256719-387e7d80-49c9-11eb-96c5-ff5b8b38b18d.png">

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/expressir-0.2.4/ext/express-parser
/Users/me/.rbenv/versions/2.6.6/bin/ruby -I /Users/me/.rbenv/versions/2.6.6/lib/ruby/2.6.0 -r
./siteconf20201229-57021-n16ta1.rb extconf.rb
checking for -lstdc++... yes
creating Makefile

current directory:
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/expressir-0.2.4/ext/express-parser
make "DESTDIR=" clean

current directory:
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/expressir-0.2.4/ext/express-parser
make "DESTDIR="
compiling express_parser.cpp
express_parser.cpp:3:10: fatal error: 'antlr4-runtime.h' file not found
#include "antlr4-runtime.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [express_parser.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/expressir-0.2.4 for inspection.
Results logged to
/Users/me/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/extensions/x86_64-darwin-19/2.6.0/expressir-0.2.4/gem_make.out

An error occurred while installing expressir (0.2.4), and Bundler cannot continue.
Make sure that `gem install expressir -v '0.2.4' --source 'https://rubygems.org/'` succeeds before
bundling.
```

**Comment by zakjan** [comment]
If there is no matching precompiled gem, these sources need to be included in gemspec for local compilation. https://github.com/camertron/antlr-gemerator/blob/master/lib/antlr-gemerator/templates/gemspec.erb#L25

**Comment by CAMOBAP** [comment]
@zakjan @ronaldtse I already solved this locally, now I trying to exclude ext directory for platform gems

**Comment by CAMOBAP** [comment]
Fix pushed we need to release this ASAP to unblock @opoudjis 

@ronaldtse we still have a problem with automated push https://github.com/lutaml/expressir/issues/36, could you please check the last comment again.

Probably we should do push manually this time, I can help with this if you will add me to the team on rubygems (`camobap` is my username on rubygems)

**Comment by CAMOBAP** [comment]
I have tested:
 - [x] macos (big sur)
 - [x] windows 10
 - [x] docker (ubuntu)

build of native extension works there

**Comment by CAMOBAP** [comment]
Actually, linux doesn't work I will push fix and release again

**Comment by ronaldtse** [comment]
I was able to install from source on macOS.

**Comment by CAMOBAP** [comment]
> I was able to install from source on macOS.

Yep but we have a serious problem with prebuilt #39 I researching it right now
