### ISSUE TITLE
Linux prebuilt get bigger then 25Mb

### ISSUE THREAD

**Issue by CAMOBAP** [lutaml/expressir#38]
A prebuilt gem on Linux is 10x bigger than on windows or macos, probably we need to strip it explicitly

Also antlr4 depends on gcc 5 or above

cc @ronaldtse

**Comment by ronaldtse** [comment]
I believe we can strip the sources in the prebuilt binary. Would that help?

**Comment by CAMOBAP** [comment]
> I believe we can strip the sources in the prebuilt binary. Would that help?

I still trying to find a proper way how to do this...

 BTW by strip I mean `strip` utility which removes debug code from the extension's shared library

**Comment by ronaldtse** [comment]
Ah, okay. Good to try.

**Comment by CAMOBAP** [comment]
- without strip express_parser.so - 36 412 120
 - after strip express_parser.so - 8 719 904

I think we should pass `-s` explicitly

**Comment by CAMOBAP** [comment]
Fixed after migration from `mkmf-rice`
