### ISSUE TITLE
Refactor code to remove Nokogiri from dependency

### ISSUE THREAD

**Issue by CAMOBAP** [lutaml/expressir#40]
- https://github.com/lutaml/expressir/blob/master/lib/expressir/express.rb#L1
 - https://github.com/lutaml/expressir/blob/master/expressir.gemspec#L36

@zakjan @ronaldtse can you confirm?

**Comment by zakjan** [comment]
It seems it's not used, the dependency might be removed instead?

**Comment by CAMOBAP** [comment]
@zakjan actually we are using it here https://github.com/lutaml/expressir/blob/master/lib/expressir/express/repository.rb#L78

**Comment by ronaldtse** [comment]
I think we no longer want to read from the XML, and can have the Nokogiri dependency removed. @zakjan can you help replace the XML work using the new parser nodes? Thanks.

**Comment by zakjan** [comment]
I might have misunderstood this, but... if XML parser is updated to use the new model, Nokogiri still stays there.

**Comment by CAMOBAP** [comment]
@zakjan thanks for the response, initially I created the issue because nokogiri was declared as development_dependency, probably we need to "promote" it to runtime_dependency

I think we can close this one

**Comment by zakjan** [comment]
Moved Nokogiri to runtime dependencies to fix this conflict until XML parser is updated.

https://github.com/lutaml/expressir/commit/f0517a226736f93a1ab0649f9cd69d4fa5bbb20c
