### ISSUE TITLE
Create native platform gems to require compilation tools

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#43]
As reported by @abunashir : https://github.com/metanorma/metanorma-cli/issues/202

It is necessary to install compilation tools to build the `expressir` gem, such as automake, g++, etc. Users of this gem should not need to do so.

@CAMOBAP is currently working on platform gems to address #42.

**Comment by CAMOBAP** [comment]
Platform gems will not require such tools anymore, there is few subtasks left in #42

**Comment by CAMOBAP** [comment]
@abunashir @ronaldtse should work now for 0.2.7 release (please reopen in you still have any issues)

**Comment by ronaldtse** [comment]
Thank you @camobap!
