### ISSUE TITLE
Release flow fails due to failed API Key interpolation

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#56]
https://github.com/lutaml/expressir/blob/7ae5967b01895b7be82427697543495142eb721a/.github/workflows/release.yml#L77

Should be:
https://github.com/metanorma/mn2pdf-ruby/blob/82ad10800869f5af7341986dfb6acbf391b062e0/.github/workflows/release.yml#L35

```
          cat > ~/.gem/credentials << EOF
```

**Comment by CAMOBAP** [comment]
Fixed, more details here https://github.com/lutaml/expressir/issues/36#issuecomment-765890460
