### ISSUE TITLE
EXPRESS source formatter buggy

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#57]
> > Re the bug, it's weird, source attribute should contain original tokens without any change. I added a test that confirms it. 
> > https://github.com/lutaml/expressir/blob/7ae5967b01895b7be82427697543495142eb721a/spec/expressir/express_exp/source_spec.rb

> > Is it possible that the string changes along the way?

I am having difficulty seeing how. I invoke

````
[source%unnumbered]
--
{{ schema.sourcecode }}
--
````

and I get:

````
<sourcecode id="_0aea3a57-938e-4049-a2a1-6f3b270ffa72" unnumbered="true">SCHEMA action_schema '{iso standard 10303 part(41) version(8) object(1) action_schema(1)}';
REFERENCE FROM basic_attribute_schema
  (description_attributedescription_attribute_selectget_description_valueget_id_valueget_name_valueget_roleid_attributeid_attribute_selectname_attributename_attribute_selectobject_rolerole_selectrole_association);
REFERENCE FROM support_resource_schema
  (bag_to_setidentifierlabeltext);
TYPE as_description_attribute_select = SELECT BASED_ON description_attribute_select WITH (action_request_solution);
END_TYPE;
....
````

schema is all one big dump of stuff. I am not doing a thing to that dump, it's a one-liner in lutaml, and I have no idea what to debug.

The fact that the commas, not just the carriage returns are being collapsed in one specific semantic class of text does make me think that this is happening in expressir; metanorma has no reason to differentiate any of those lines, and certainly doesn't touch punctuation.

_Originally posted by @opoudjis in https://github.com/lutaml/expressir/issues/53#issuecomment-766312898_

**Comment by zakjan** [comment]
Fixed in https://github.com/lutaml/expressir/commit/6588186bfc3a47a86d2debf664aa7fbd6e1bba51
