### ISSUE TITLE
Documentation: How to obtain EXPRESS schema version string

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#71]
Needed in https://github.com/metanorma/annotated-express/issues/22

e.g., need to fetch version string of schema `{ iso standard 10303 part(41) version(8) object(1) action-schema(1) }` when given parsed schema `action_schema`

Schema:
```
SCHEMA action_schema '{iso standard 10303 part(41) version(8) object(1) action_schema(1)}';
```

**Comment by zakjan** [comment]
It is available in [Schema.version](https://github.com/lutaml/expressir/blob/master/lib/expressir/model/schema.rb#L8)

**Comment by ronaldtse** [comment]
@zakjan can you help add this in the README? Thanks.

**Comment by zakjan** [comment]
Created #72 for choosing a documentation approach for Express model classes.
