### ISSUE TITLE
Express model documentation

### ISSUE THREAD

**Issue by zakjan** [lutaml/expressir#72]
Currently, there is no explicit Express model documentation. All available classes, members, and usage can be seen directly in [model classes](https://github.com/lutaml/expressir/tree/master/lib/expressir/model) and [sample input file](https://github.com/lutaml/expressir/blob/master/original/examples/syntax/syntax.exp) + [parser test](https://github.com/lutaml/expressir/blob/master/spec/expressir/express_exp/parser/syntax_spec.rb).

How shall we document it? Separate AsciiDoc file? RDoc?

**Comment by ronaldtse** [comment]
Something like this https://github.com/fontist/fontist to start with?

**Comment by zakjan** [comment]
Parser test was replaced by [YAML export](https://github.com/lutaml/expressir/blob/master/original/examples/syntax/syntax.yaml).

**Comment by zakjan** [comment]
After a short research of possible methods, I'm going to use [YARD](https://yardoc.org/index.html), because of its support for structured documentation tags and macros.

**Comment by zakjan** [comment]
Sneak peak

![Screen Shot 2021-04-18 at 22 50 54](https://user-images.githubusercontent.com/173585/115160470-94fcca00-a098-11eb-8860-12b48c31aa45.png)

It's likely going to need further changes in model structure, add abstract classes, e.g. Expression
