### ISSUE TITLE
SELECT: Ability to provide schema information of referenced items

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#75]
document_schema.exp
```
  TYPE product_or_formation_or_definition = SELECT (product, product_definition_formation, product_definition);
  END_TYPE;
```

In the Select object, we want to create a hyperlink to `product_definition_formation`, which actually originates from the `product_definition_schema`.

The method we build the hyperlink is via: `<<express:{schema}:{object}>>`, so we need the `{schema}` name in order to make this reference.

**Comment by ronaldtse** [comment]
Is this same as #76 ?

**Comment by zakjan** [comment]
Yes, this is the same.
