### ISSUE TITLE
Add specs for "REFERENCE/USE FROM" in model_element_spec.rb

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#82]
In the specs now there are no tests for "REFERENCE FROM" and "USE FROM" in model_element_spec.rb.

We should add them.

**Comment by zakjan** [comment]
Added tests for ModelElement.find to find items included by interface declarations.

https://github.com/lutaml/expressir/blob/7a55a7ec529633ca6f15e0df64990f59295b198e/spec/expressir/model/model_element_spec.rb#L88-L108
