### ISSUE TITLE
(URGENT) Upgrade rice gem to 4.0

### ISSUE THREAD

**Issue by ronaldtse** [lutaml/expressir#95]
Required for packed-mn. (also from https://github.com/tamatebako/tebako/issues/55)

**Comment by ronaldtse** [comment]
Reason for failure: https://github.com/metanorma/packed-mn/issues/140

**Comment by alexeymorozov** [comment]
As I see, it requires to rewrite the `antlr4-native` gem with a support of rice v4:

https://github.com/camertron/antlr4-native-rb/blob/master/lib/antlr4-native/generator.rb#L77

Will fork and do a PR.

**Comment by alexeymorozov** [comment]
Fork is here: https://github.com/camertron/antlr4-native-rb/compare/master...alexeymorozov:rice-4
